extends:
  [
    "stylelint-config-standard-scss",
    "stylelint-config-prettier-scss",
    "stylelint-config-standard",
    "stylelint-config-standard",
    "stylelint-config-prettier",
  ]

plugins: ["stylelint-order", "stylelint-scss"]
