/* eslint-disable prettier/prettier */
// eslint-disable-next-line no-unused-vars
export let cards = [
  {
    number: 6,
    suit: 'peaks',
    sourse: '../cards_images/6%20бубны.svg',
    id: 1,
  },
  {
    number: 7,
    suit: 'peaks',
    sourse: '../cards_images/7%20пики.svg',
    id: 2,
  },
  {
    number: 8,
    suit: 'peaks',
    sourse: '../cards_images/8%20пики.svg',
    id: 3,
  },
  {
    number: 9,
    suit: 'peaks',
    sourse: '../cards_images/9%20пики.svg',
    id: 4,
  },
  {
    number: 10,
    suit: 'peaks',
    sourse: '../cards_images/10%20пики.svg',
    id: 5,
  },
  {
    number: 11,
    suit: 'peaks',
    sourse: '../cards_images/валет%20пики.svg',
    id: 6,
  },
  {
    number: 12,
    suit: 'peaks',
    sourse: '../cards_images/дама%20пики.svg',
    id: 7,
  },
  {
    number: 13,
    suit: 'peaks',
    sourse: '../cards_images/король%20пики.svg',
    id: 8,
  },
  {
    number: 14,
    suit: 'peaks',
    sourse: '../cards_images/туз%20пики.svg',
    id: 9,
  },
  {
    number: 6,
    suit: 'hearts',
    sourse: '../cards_images/6%20черви.svg',
    id: 10,
  },
  {
    number: 7,
    suit: 'hearts',
    sourse: '../cards_images/7%20черви.svg',
    id: 11,
  },
  {
    number: 8,
    suit: 'hearts',
    sourse: '../cards_images/8%20черви.svg',
    id: 12,
  },
  {
    number: 9,
    suit: 'hearts',
    sourse: '../cards_images/9%20черви.svg',
    id: 13,
  },
  {
    number: 10,
    suit: 'hearts',
    sourse: '../cards_images/10%20черви.svg',
    id: 14,
  },
  {
    number: 11,
    suit: 'hearts',
    sourse: '../cards_images/валет%20черви.svg',
    id: 15,
  },
  {
    number: 12,
    suit: 'hearts',
    sourse: '../cards_images/дама%20черви.svg',
    id: 16,
  },
  {
    number: 13,
    suit: 'hearts',
    sourse: '../cards_images/король%20черви.svg',
    id: 17,
  },
  {
    number: 14,
    suit: 'hearts',
    sourse: '../cards_images/туз%20черви.svg',
    id: 18,
  },
  {
    number: 6,
    suit: 'baptize',
    sourse: '../cards_images/6%20крести.svg',
    id: 19,
  },
  {
    number: 7,
    suit: 'baptize',
    sourse: '../cards_images/7%20крести.svg',
    id: 20,
  },
  {
    number: 8,
    suit: 'baptize',
    sourse: '../cards_images/8%20крести.svg',
    id: 21,
  },
  {
    number: 9,
    suit: 'baptize',
    sourse: '../cards_images/9%20крести.svg',
    id: 22,
  },
  {
    number: 10,
    suit: 'baptize',
    sourse: '../cards_images/10%20крести.svg',
    id: 23,
  },
  {
    number: 11,
    suit: 'baptize',
    sourse: '../cards_images/валет%20крести.svg',
    id: 24,
  },
  {
    number: 12,
    suit: 'baptize',
    sourse: '../cards_images/дама%20крести.svg',
    id: 25,
  },
  {
    number: 13,
    suit: 'baptize',
    sourse: '../cards_images/король%20крести.svg',
    id: 26,
  },
  {
    number: 14,
    suit: 'baptize',
    sourse: '../cards_images/туз%20крести.svg',
    id: 27,
  },
  {
    number: 6,
    suit: 'diamonds',
    sourse: '../cards_images/6%20бубны.svg',
    id: 28,
  },
  {
    number: 7,
    suit: 'diamonds',
    sourse: '../cards_images/7%20бубны.svg',
    id: 29,
  },
  {
    number: 8,
    suit: 'diamonds',
    sourse: '../cards_images/8%20бубны.svg',
    id: 30,
  },
  {
    number: 9,
    suit: 'diamonds',
    sourse: '../cards_images/9%20бубны.svg',
    id: 31,
  },
  {
    number: 10,
    suit: 'diamonds',
    sourse: '../cards_images/10%20бубны.svg',
    id: 32,
  },
  {
    number: 11,
    suit: 'diamonds',
    sourse: '../cards_images/валет%20бубны.svg',
    id: 33,
  },
  {
    number: 12,
    suit: 'diamonds',
    sourse: '../cards_images/дама%20бубны.svg',
    id: 34,
  },
  {
    number: 13,
    suit: 'diamonds',
    sourse: '../cards_images/король%20бубны.svg',
    id: 35,
  },
  {
    number: 14,
    suit: 'diamonds',
    sourse: '../cards_images/туз%20бубны.svg',
    id: 36,
  },
]
